version: "3.1"
services:
  web:
    stdin_open: true
    tty: true
    volumes:
      - .:/snackbox
    environment:
      - RAILS_ENV=development
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
