version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    volumes:
      - .:/my_app
    ports:
      - "3000:3000"
    depends_on:
      - db