version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    stdin_open: true
    tty: true
    build: .
    volumes:
      - .:/snackbox
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      ADMIN_USERNAME: username
      ADMIN_PASSWORD: password
      BASE_URL: http://localhost:3000
      CONTACT_EMAIL: awayte@teladochealth.com
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"