version: "3.1"
services:
  web:
    stdin_open: true
    tty: true
    links:
      - db
      - webpacker
    volumes:
      - .:/snackbox
    environment:
      - RAILS_ENV=development
  sidekiq:
    volumes:
      - .:/snackbox
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
  webpacker:
    build:
      context: .
    command: ["/usr/bin/scripts/start_webpack_dev.sh"]
    volumes:
      - .:/snackbox
    ports:
      - "3035:3035"
