version: "3.1"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - RAILS_ENV=production
      - PORT=8080
      - REDIS_URL=redis://redis:6379/1
      - RAILS_LOG_TO_STDOUT=ENABLE
    entrypoint: /usr/bin/scripts/entrypoint.sh
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    image: "redis:6.2.1-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
    hostname: redis
  sidekiq:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1
    entrypoint: /usr/bin/scripts/sidekiq_entrypoint.sh
volumes:
  redis:
  db:
