# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USERNAME"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "password" %>
  pool: <%= ENV['RAILS_MAX_THREADS'] || Sidekiq.options[:concurrency] %>
  host: <%= ENV["POSTGRES_HOST"] || "db" %>
  port: <%= ENV["POSTGRES_PORT"] || 5432 %>

development:
  <<: *default
  database: snackbox_development

test:
  <<: *default
  database: snackbox_test

production:
  <<: *default
  database: snackbox_production
